### ISSUE TITLE
Scanner didn't confirm transaction

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#712] opened 2020-10-12 19:20 UTC
Problematic TX: https://live.blockcypher.com/btc/tx/e2b3a88d8ef0aa39289b038ffdb2a9df2af75e63f2788bb14c41793dbb81644a/

1. Check that indexers have blocks for the tx.
2. Check operation of scanner for new blocks.

**Comment by fastpok** [comment] 2020-10-13 17:32
Investigation has shown that the problem is in obtaining filters.
When wallet tries to get fresh filters from indexer, connection hangs.

Indexer throws the following error message:
`ergvein-index-server: writev: resource vanished (Broken pipe)`

**Comment by fastpok** [comment] 2020-10-21 18:40
It looks like the problem is closely related to getting heights from bitcoin nodes

**Comment by fastpok** [comment] 2020-10-23 17:07
The main problem, most likely, is the incorrect deserialization of the `MFiltersEvent` messages.

**Comment by fastpok** [comment] 2020-10-26 11:43
Closing this for now.

**Comment by fastpok** [comment] 2020-10-26 17:38
The problem was caused by the `getOpenSyncedConns` function not working properly. The height on the side of the wallet was miscalculated.

**Closed** 2020-10-26 20:39 UTC
Labels: bug, critical
